cbb_mappings = {
    "Duke Blue Devils": "DUKE",
    "North Carolina Tar Heels": "UNC",
    "Kentucky Wildcats": "UK",
    "Kansas Jayhawks": "KU",
    "Michigan State Spartans": "MSU",
    "Villanova Wildcats": "VILL",
    "Virginia Cavaliers": "UVA",
    "Gonzaga Bulldogs": "GONZ",
    "Texas Tech Red Raiders": "TTU",
    "Auburn Tigers": "AUB",
    "Florida State Seminoles": "FSU",
    "Houston Cougars": "HOU",
    "Iowa State Cyclones": "ISU",
    "LSU Tigers": "LSU",
    "Maryland Terrapins": "MD",
    "Buffalo Bulls": "BUFF",
    "Central Florida Knights": "UCF",
    "Cincinnati Bearcats": "CINCY",
    "Colgate Raiders": "COLG",
    "Florida Gators": "UF",
    "Iowa Hawkeyes": "IOWA",
    "Kansas State Wildcats": "KSU",
    "Louisville Cardinals": "LOU",
    "Murray State Racers": "MUR",
    "Nevada Wolf Pack": "NEV",
    "New Mexico State Aggies": "NMSU",
    "Northeastern Huskies": "NE",
    "Ohio State Buckeyes": "OSU",
    "Oklahoma Sooners": "OU",
    "Old Dominion Monarchs": "ODU",
    "Oregon Ducks": "ORE",
    "Saint Louis Billikens": "SLU",
    "Seton Hall Pirates": "SHU",
    "Syracuse Orange": "SYR",
    "UC Irvine Anteaters": "UCI",
    "UCF Knights": "UCF",
    "Utah State Aggies": "USU",
    "VCU Rams": "VCU",
    "Vermont Catamounts": "UVM",
    "Villanova Wildcats": "VILL",
    "Virginia Cavaliers": "UVA",
    "Washington Huskies": "WASH",
    "Wisconsin Badgers": "WISC",
    "Wofford Terriers": "WOF",
    "Yale Bulldogs": "YALE",
    "Loyola Chicago Ramblers": "LUC",
}
