nba_mappings = {
    "Los Angeles Lakers": "LAL",
    "Los Angeles Clippers": "LAC",
    "Golden State Warriors": "GSW",
    "Phoenix Suns": "PHX",
    "Sacramento Kings": "SAC",
    "Dallas Mavericks": "DAL",
    "Houston Rockets": "HOU",
    "San Antonio Spurs": "SAS",
    "Memphis Grizzlies": "MEM",
    "New Orleans Pelicans": "NOP",
    "Portland Trail Blazers": "POR",
    "Utah Jazz": "UTA",
    "Denver Nuggets": "DEN",
    "Minnesota Timberwolves": "MIN",
    "Oklahoma City Thunder": "OKC",
    "Milwaukee Bucks": "MIL",
    "Chicago Bulls": "CHI",
    "Indiana Pacers": "IND",
    "Detroit Pistons": "DET",
    "Cleveland Cavaliers": "CLE",
    "Toronto Raptors": "TOR",
    "Boston Celtics": "BOS",
    "Philadelphia 76ers": "PHI",
    "Brooklyn Nets": "BKN",
    "New York Knicks": "NYK",
    "Orlando Magic": "ORL",
    "Miami Heat": "MIA",
    "Washington Wizards": "WAS",
    "Charlotte Hornets": "CHA",
    "Atlanta Hawks": "ATL",
    "Golden State Warriors": "GSW",
}
