team_mappings = {
        'MLB': {
            "New York Yankees": "NYY",
            "Boston Red Sox": "BOS",
            "Chicago Cubs": "CHC",
            "Los Angeles Dodgers": "LAD",
            "San Francisco Giants": "SF",
            "Houston Astros": "HOU",
            "Washington Nationals": "WSH",
            "St. Louis Cardinals": "STL",
            "Philadelphia Phillies": "PHI",
            "New York Mets": "NYM",
            "Chicago White Sox": "CWS",
            "Los Angeles Angels": "LAA",
            "Minnesota Twins": "MIN",
            "Texas Rangers": "TEX",
            "Atlanta Braves": "ATL",
            "Cleveland Indians": "CLE",
            "Oakland Athletics": "OAK",
            "Pittsburgh Pirates": "PIT",
            "San Diego Padres": "SD",
            "Seattle Mariners": "SEA",
            "Detroit Tigers": "DET",
            "Arizona Diamondbacks": "ARI",
            "Toronto Blue Jays": "TOR",
            "Milwaukee Brewers": "MIL",
            "Kansas City Royals": "KC",
            "Colorado Rockies": "COL",
            "Baltimore Orioles": "BAL",
            "Miami Marlins": "MIA",
            "Tampa Bay Rays": "TB",
            "Cincinnati Reds": "CIN",
            # ... other MLB teams
        },
        
        'NFL': {
            "Washington Redskins": "WAS",
            "New York Giants": "NYG",
            "Dallas Cowboys": "DAL",
            "Philadelphia Eagles": "PHI",
            "Green Bay Packers": "GB",
            "Chicago Bears": "CHI",
            "Detroit Lions": "DET",
            "Minnesota Vikings": "MIN",
            "Atlanta Falcons": "ATL",
            "New Orleans Saints": "NO",
            "Carolina Panthers": "CAR",
            "Tampa Bay Buccaneers": "TB",
            "San Francisco 49ers": "SF",
            "Seattle Seahawks": "SEA",
            "Los Angeles Rams": "LAR",
            "Arizona Cardinals": "ARI",
            "New England Patriots": "NE",
            "Miami Dolphins": "MIA",
            "Buffalo Bills": "BUF",
            "New York Jets": "NYJ",
            "Baltimore Ravens": "BAL",
            "Pittsburgh Steelers": "PIT",
            "Cleveland Browns": "CLE",
            "Cincinnati Bengals": "CIN",
            "Houston Texans": "HOU",
            "Indianapolis Colts": "IND",
            "Jacksonville Jaguars": "JAX",
            "Tennessee Titans": "TEN",
            "Kansas City Chiefs": "KC",
            "Los Angeles Chargers": "LAC",
            "Denver Broncos": "DEN",
            "Las Vegas Raiders": "LV",
            # ... other NFL teams
        },
        'NBA': {
            "Los Angeles Lakers": "LAL",
            "Los Angeles Clippers": "LAC",
            "Golden State Warriors": "GSW",
            "Phoenix Suns": "PHX",
            "Sacramento Kings": "SAC",
            "Dallas Mavericks": "DAL",
            "Houston Rockets": "HOU",
            "San Antonio Spurs": "SAS",
            "Memphis Grizzlies": "MEM",
            "New Orleans Pelicans": "NOP",
            "Portland Trail Blazers": "POR",
            "Utah Jazz": "UTA",
            "Denver Nuggets": "DEN",
            "Minnesota Timberwolves": "MIN",
            "Oklahoma City Thunder": "OKC",
            "Milwaukee Bucks": "MIL",
            "Chicago Bulls": "CHI",
            "Indiana Pacers": "IND",
            "Detroit Pistons": "DET",
            "Cleveland Cavaliers": "CLE",
            "Toronto Raptors": "TOR",
            "Boston Celtics": "BOS",
            "Philadelphia 76ers": "PHI",
            "Brooklyn Nets": "BKN",
            "New York Knicks": "NYK",
            "Orlando Magic": "ORL",
            "Miami Heat": "MIA",
            "Washington Wizards": "WAS",
            "Charlotte Hornets": "CHA",
            "Atlanta Hawks": "ATL",
            "Golden State Warriors": "GSW",
            # ... other NBA teams
        },
        'College Basketball': {
            "Duke Blue Devils": "DUKE",
            "North Carolina Tar Heels": "UNC",
            "Kentucky Wildcats": "UK",
            "Kansas Jayhawks": "KU",
            "Michigan State Spartans": "MSU",
            "Villanova Wildcats": "VILL",
            "Virginia Cavaliers": "UVA",
            "Gonzaga Bulldogs": "GONZ",
            "Texas Tech Red Raiders": "TTU",
            "Auburn Tigers": "AUB",
            "Florida State Seminoles": "FSU",
            "Houston Cougars": "HOU",
            "Iowa State Cyclones": "ISU",
            "LSU Tigers": "LSU",
            "Maryland Terrapins": "MD",
            "Buffalo Bulls": "BUFF",
            "Central Florida Knights": "UCF",
            "Cincinnati Bearcats": "CINCY",
            "Colgate Raiders": "COLG",
            "Florida Gators": "UF",
            "Iowa Hawkeyes": "IOWA",
            "Kansas State Wildcats": "KSU",
            "Louisville Cardinals": "LOU",
            "Murray State Racers": "MUR",
            "Nevada Wolf Pack": "NEV",
            "New Mexico State Aggies": "NMSU",
            "Northeastern Huskies": "NE",
            "Ohio State Buckeyes": "OSU",
            "Oklahoma Sooners": "OU",
            "Old Dominion Monarchs": "ODU",
            "Oregon Ducks": "ORE",
            "Saint Louis Billikens": "SLU",
            "Seton Hall Pirates": "SHU",
            "Syracuse Orange": "SYR",
            "UC Irvine Anteaters": "UCI",
            "UCF Knights": "UCF",
            "Utah State Aggies": "USU",
            "VCU Rams": "VCU",
            "Vermont Catamounts": "UVM",
            "Villanova Wildcats": "VILL",
            "Virginia Cavaliers": "UVA",
            "Washington Huskies": "WASH",
            "Wisconsin Badgers": "WISC",
            "Wofford Terriers": "WOF",
            "Yale Bulldogs": "YALE",
            "Loyola Chicago Ramblers": "LUC",
            # ... other college basketball teams
        
        },
        # ... other sports
    }